### ISSUE TITLE
ValueError: invalid format for access token

### ISSUE THREAD

**Issue by Microfi** [Emilv2/stib_mivb#10]
I just tried setting up the stib_mivb sensor, and I'm getting the following error message in my logs:

```
2024-01-18 11:27:50.086 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up stib_mivb platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/stib_mivb/sensor.py", line 66, in async_setup_platform
    api = ODStibMivb(api_key, session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyodstibmivb/odstibmivb.py", line 43, in __init__
    self.access_token = access_token
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyodstibmivb/odstibmivb.py", line 61, in access_token
    raise ValueError("invalid format for access token")
ValueError: invalid format for access token
```

... what's strange about this, is that I see that my quota of requests is going up, when I check the OpenData dashboard for STIB/MIVB. This should normally mean that the API calls are successful, right?

Any insight in what I might be doing wrong here? Thank you in advance!

**Comment by danito** [comment]
Hi,
I'm afraid that it's using an outdated parameter to connect to the stib api (via https://gitlab.com/Emilv2/pyodstibmivb).
(you can look at https://github.com/danito/stibgtfs2mqtt, if you have a way to run a python script and connect to a mqtt server, it creates a sensor for each line passing at a given stop).

**Comment by Microfi** [comment]
> Hi, I'm afraid that it's using an outdated parameter to connect to the stib api (via https://gitlab.com/Emilv2/pyodstibmivb). (you can look at https://github.com/danito/stibgtfs2mqtt, if you have a way to run a python script and connect to a mqtt server, it creates a sensor for each line passing at a given stop).

Thanks for your reply, danito. So I can assume this integration is currently broken?
I'll see if I can host a small alpine lxc to run your python script on!
