### ISSUE TITLE
stib_mivb: Error on device update!

### ISSUE THREAD

**Issue by tebra-jl** [Emilv2/stib_mivb#2]
Hi @Emilv2 
I follow the instructions to install this custom integration but when I try to restart homeassistant I get this error "stib_mivb: Error on device update!" on log.

My Access token from opendata.stib-mivb.be is incorrect ?

Here is the log:
Logger: homeassistant.components.sensor
Source: custom_components/stib_mivb/sensor.py:105
Integration: Capteur (documentation, issues)
First occurred: 17:16:09 (1 occurrences)
Last logged: 17:16:09

stib_mivb: Error on device update!
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/home/homeassistant/homeassistant/custom_components/stib_mivb/sensor.py", line 105, in async_update
    stop_name = await self.api.get_point_detail(self.stop_id)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 235, in get_point_detail
    return await self.do_request("point_detail", id_, *ids)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 151, in do_request
    return await self.get_response_unlimited(self._session, method, id_, *ids)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 169, in get_response_unlimited
    response = await self.get_response(session, url)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 197, in get_response
    raise HttpException(message, await response.text(), response.status)
pyodstibmivb.odstibmivb.HttpException: 403: incorrect API request

**Comment by Emilv2** [comment]
Subscribe to the NetworkDescription and OperationMonitoring on the [apis page](https://opendata.stib-mivb.be/store/apis/info?)

**Comment by tebra-jl** [comment]
Thanks for your help.
Ok, now I have subscribed to NetworkDescription and OperationMonitoring but I get this:

Logger: homeassistant.components.sensor
Source: custom_components/stib_mivb/sensor.py:105 
Integration: Capteur (documentation, issues) 
First occurred: 0:41:19 (1 occurrences) 
Last logged: 0:41:19

stib_mivb: Error on device update!
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/home/homeassistant/homeassistant/custom_components/stib_mivb/sensor.py", line 105, in async_update
    stop_name = await self.api.get_point_detail(self.stop_id)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 235, in get_point_detail
    return await self.do_request("point_detail", id_, *ids)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 151, in do_request
    return await self.get_response_unlimited(self._session, method, id_, *ids)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 169, in get_response_unlimited
    response = await self.get_response(session, url)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pyodstibmivb/odstibmivb.py", line 201, in get_response
    raise HttpException(message, await response.text(), response.status)
pyodstibmivb.odstibmivb.HttpException: Unexpected status code 500.

**Comment by tebra-jl** [comment]
After rebooting HA today I get a different error message in log:

Logger: homeassistant.components.sensor
Source: custom_components/stib_mivb/sensor.py:129 
Integration: Capteur (documentation, issues) 
First occurred: 09:29:56 (1 occurrences) 
Last logged: 09:29:56

stib_mivb: Error on device update!
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 618, in async_device_update
    await task
  File "/home/homeassistant/homeassistant/custom_components/stib_mivb/sensor.py", line 129, in async_update
    for passing_time in waiting_time_response["points"][0]["passingTimes"]:
IndexError: list index out of range


Here is my configuration.yaml
sensor:
  - platform: stib_mivb
    api_key: '!secret'
    lang: 'fr'
    message_lang: 'fr'
    stops:
      - stop_id: 8231
        line_numbers:
          - 5

**Comment by Emilv2** [comment]
I can reproduce this, I'll take a look at it

**Comment by Emilv2** [comment]
Hmm, I was too quick in replying and made an error when copying. It works for me. Seems like you got an empty response from STIB, IIRC that is not supposed to happen even when there is no service at the moment. Maybe there was something wrong with the servers at the moment you ran it? That happens from time to time. Does it still not work?

**Comment by tebra-jl** [comment]
Hi, after a reboot of HA today it works. Strange
Now I have a sensor with line info. Thanks
