### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by arthurmagnus** [Emilv2/stib_mivb#6]
Hi @Emilv2,

I followed your instructions to add your custom component to my HA installation. However, when I restart HA I get the following error:

> Logger: homeassistant.components.sensor
Source: custom_components/stib_mivb/sensor.py:129
Integration: Sensor (documentation, issues)
First occurred: 10:00:44 (1 occurrences)
Last logged: 10:00:44

> stib_mivb: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/stib_mivb/sensor.py", line 129, in async_update
    for passing_time in waiting_time_response["points"][0]["passingTimes"]:
IndexError: list index out of range `

I created a temporary solution by using a restful sensor and querying the API directly, so my API access token doesn't seem to be the problem.

Any ideas on how to fix this?

**Comment by arthurmagnus** [comment]
Actually the problem seemed to be the stop ID. For some reason the STIB adds an 'F' to the stop ID on my stop. 
So instead of stop ID **xxxx** it's stop ID **xxxxF** on their API. Strange, but it works now! 

I found out by testing some requests on their API. I could get the passing times through the */PassingTimeByPoint/{ids}* endpoint with only the **xxxx** stop ID. But when requesting more information about the stop on the */PointDetail/{ids}* endpoint I got an error. 

By requesting the stop ID's from my tram line through the */PointByLine/{ids}* endpoint I found the ID's in the **xxxxF** format.
